@startuml
autonumber

actor "MedicalLabTechnician" as MLT
participant "System" as SYS

activate MLT

MLT -> SYS : initiates the record of a sample
activate SYS

SYS -> MLT : shows a list of tests that have samples to be recorded
deactivate SYS

MLT -> SYS : selects a test and specifies the number of samples
activate SYS

SYS -> MLT : shows the generated barcode of each sample
deactivate SYS

@enduml
