@startuml

skinparam classAtributionIconSize 0


class ImportTestsUI {
}

class ImportTestsController {
    +ImportTestsController(company)
}

class ReflectorUtility {

  }

class Company {
}

class Employee {
}

class LaboratoryCoordinator {
}



ImportTestsController "*" ..> "1" Company : belongs to
class LaboratoryCoordinator extends Employee

@enduml