@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor  "Administrator" as Admin

Admin -> System: starts to register new laboratory
System -> Admin: requests data (labID, name, address, phoneNR, TIN)

Admin -> System: types requested data
System -> Admin: shows the data, requests confirmation and shows the list of tests

Admin -> System: confirms data and chooses tests
System -> Admin: shows the chosen tests and requests confirmation

Admin -> System: Confirms the chosen tests
System -> Admin: Informs success
@enduml