@startuml

skinparam classAtributionIconSize 0

class RegisterLaboratoryIU

class RegisterLaboratoryController {
    +registerLab(LabID, address, phoneNumber, TIN)
    +saveLab()
    +registerTest(sample)
    +saveTest()
}

class Clinic {
    +registerTest(sample)
    +saveTest()
    +validateTest()
    +addTest()
  }

class Company {
    +registerLab(LabID, address, phoneNumber, TIN)
    +saveLab()
    +validateLab()
    +addLab()

}

@enduml
