@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Admin"

Admin -> RegisterLaboratoryIU: starts the registry of a new Clinical Analysis Laboratory and tests
RegisterLaboratoryIU --> Admin: request data (labID, name, address, phoneNr, TIN)

Admin -> RegisterLaboratoryIU: types requested data
RegisterLaboratoryIU --> RegisterLaboratoryController: registerLab(labID,name, address, phoneNr, TIN)


@enduml