@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor  "Admin"

Admin -> System: starts to register new laboratory
System --> Admin: requests data (labID, name, address, phoneNR, TIN)

Admin -> System: types requested data
System --> Admin: shows the data and requests confirmation

Admin -> System: confirms data
System --> Admin: informs success
@enduml