@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor  "Laboratory Cordinator" as LC

participant System

activate LC


LC -> System: wants to have an overview of the tests performed
activate System

System -> LC: shows the tests that were performed and asks to know which Graphs and Statistics that he wants to see


deactivate System
LC -> System: selects the requested date Interval

activate System

System -> LC: asks to confirm the date Interval

deactivate System

LC -> System: confirms data
activate System
System -> LC: informs success or insuccess of the operation

deactivate System

@enduml
