@startuml

object Company{
}

object Test{
}


object Clinic{
}

object Parameter{
}

object Category{
}

object Administrator{
}

object Sample{
}

object Report{
}

object MedicalLabTechnician{
}

object SpecialistDoctor{
}

object LaboratoryCoordinator{
}

object Client{
}

object Administrator{
}

object Receptionist{
}

object ClinicalChemistryTechnologist{
}

object ChemicalLaboratory{
}

object DailyReport{
}

object CovidReport{
}


Company "1" -- "*" Test : performs
Company "1" -- "*" Clinic : has
Company "1" -- "1" ChemicalLaboratory : has
Parameter "1" -- "*" Category : is presented under
Category "1" -- "1" Administrator : is created by
Test "*" -- "1" Client : is requested by
Test "*" -- "1" Category : is of
Sample "*" -- "1" MedicalLabTechnician : is analyzed by
Report "*" -- "1" ClinicalChemistryTechnologist : is written by
Report "*" -- "1" MedicalLabTechnician : is written by
Report "*" -- "1" SpecialistDoctor : is written by
Report "*" -- "1" LaboratoryCoordinator : is written by
Report "1" -- "1" Test : is based on
Report "*" -- "1" Client : is sent to
Administrator "1" -- "*" Test : specifies
Receptionist "1" -- "*" Client : registers
Receptionist "1" -- "*" Test : registers
LaboratoryCoordinator "1" -- "*" Report : validates
ChemicalLaboratory "1" -- "*" Sample : is received
ClinicalChemistryTechnologist "1" -- "*" Sample : registers the result
ChemicalLaboratory "1" -- "*" Sample : it's where it analyzes
ChemicalLaboratory "1" -- "*" Report : it's where it writes
Clinic "1" -- "*" Sample : it's where are collected
DailyReport "1" -- "1" DailyReport : writes
CovidReport "1" -- "1" Someone : is done by

@enduml
Administrator "1"-- "1" Pharmacy : creates
Courier "1"--"0..1" ParkingSpace : can reserve - um courier pode reservar ponto de abastecimento????
ParkingSpace "1"--"*" Courier : sends notifications
RegisteredUser "1"--"*" Product : views
object NonRegisteredUser
NonRegisteredUser "1"--"1" RegisteredUser : registers as
NonRegisteredUser "1"--"*" Product : views
