@startuml
left to right direction

:Doctor: --> (precribes lab order)

:Receptionist: --> (registers the test to be performed)
:Receptionist: --> (registers the client)

:Chemistry topologist: --> (receives the samples)
:Chemistry topologist: --> (registers the result of the samples)

:Medical Lab Technician: --> (collects samples)
:Medical Lab Technician: --> (associates samples in the system between client/test)

:Specialist Doctor: --> (writes reports)

:Laboratory Coordinator: --> (validates reports)

:Client: --> (receives reports)

:Administrator: --> (specify new type of test and its collecting methods)
:Administrator: --> (specify new test parameter and categorize it)
:Administrator: --> (specify new parameter category)


@enduml
