@startuml
left to right direction

:Receptionist: --> (registers the test to be performed)
:Receptionist: --> (registers the client)

:Chemistry Technologist: --> (receives the samples)
:Chemistry Technologist: --> (registers the result of the samples)

:Medical Lab Technician: --> (collects samples)

:Specialist Doctor: --> (diagnostics/writes reports)

:Laboratory Coordinator: --> (validates reports)

:Client: --> (views the reports/examination)

:Administrator: --> (specify new type of test and its collecting methods)
:Administrator: --> (specify new test parameter and categorize it)
:Administrator: --> (specify new parameter category)

:Time: --> (generate daily report)

@enduml
