@startuml
left to right direction

:Receptionist: --> (registers the test to be performed)
:Receptionist: --> (registers the client)

:Chemistry Technologist: --> (registers the result of the samples)
:Chemistry Technologist: --> (verifies report)

:Medical Lab Technician: --> (collects samples)
:Medical Lab Technician: --> (verifies report)

:Specialist Doctor: --> (diagnostics sample)
:Specialist Doctor: --> (verifies report)

:Laboratory Coordinator: --> (validates/verifies reports)

:Client: --> (views the reports/examination)

:Administrator: --> (specify new type of test and its collecting methods)
:Administrator: --> (specify new test parameter and categorize it)
:Administrator: --> (specify new parameter category)

:Time: --> (generate daily report)

@enduml
