@startuml
autonumber

actor "MedicalLabTechnician" as MLT
participant "System" as SYS

activate MLT


MLT -> SYS : initiates the record of a sample
activate SYS

SYS -> MLT : requests the data required (testID, barCode, type)
deactivate SYS

MLT -> SYS : inserts the requested data
activate SYS

SYS -> MLT : shows the data and requests a confirmation
deactivate SYS

MLT -> SYS : confirms the data
activate SYS
SYS -> MLT : informs operation success

deactivate SYS

@enduml
