@startuml

object Company{
-designation
-address
}

object Sample{
-barCode
}

object Test{
-testID
-nhscode
-description
-dateDiagnosis
-timeDiagnosis
-dateValidation
-timeValidation
}

object BarCodeAPI{
}


Company "1" -- "*" Test : performs

Sample "*" -- "1" Test : is based on

package "BarCodeAPI" #DDDDDD{
	BarCodeAPI "1" -- "*" Sample : generates barCode
}


@enduml
