@startuml
class RecordSamplesUI {
 -show(freeTestsDTO)
 -show(samplesDTO)
}

class RecordSamplesController {
  +List<Test> freeTests
  +List<TestDTO> freeTestsDTO
  +generateSamples(int testIndex, int numSamples)
}

class Company {
  +List<Test> getTests()
}

RecordSamplesController ..> Company

class Test {

}

Company "1" --> "*" Test

class Sample {

}

Test "1" --> "*" Sample

class Barcode {
 -generateBarcode(code)
}

Sample "1" --> "1" Barcode

BarcodeInterface

ReflectorUtility

BarcodeAdapter

RecordSamplesUI ..> RecordSamplesController


@enduml

