@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor  "Specialist Doctor" as Spec

Spec -> System: starts to to write a diagnosis report of a given test
System --> Spec: requests data (diagnosis))

Spec -> System: types requested data (diagnosis)
System --> Spec: shows the data and requests confirmation

Spec -> System: confirms data
System --> Spec: informs success or insuccess
@enduml